### ISSUE TITLE
Let user choose RowID or another id column in Spatial Weights node

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#110]
As a user I want to specify the id column that should be used in the resulting table of the Spatial Weights node. Currently the node uses the RowID. This was requested by a user in the [forum](https://forum.knime.com/t/geospatial-extension-test-problems-and-bugs/59240).

Add a new Focal column selection parameter that also allows to select the RowID (default) to let the user choose a column that is used as focal column.

**Comment by wybert** [comment]
@koettert @UrbanGISer I think it makes no sense to let the user select the ID column for calculating the spatial weight. Bc the calculation in the flowing modeling nodes will always use the default one (ie. they use [0, the_rows_of_the_data]).

But what we can do is we can append two columns of the focal_id, and neibour_id if the user wants to set the ID column and identify which column reflect which data of the input easily.
