### ISSUE TITLE
 Geospatial View node: add None to base map, set stroke parameter, set default value

### ISSUE THREAD

**Issue by UrbanGISer** [spatial-data-lab/knime-geospatial-extension#118]
(1)  Add None to the base map option

for Stroke
(2) Add an option to stroke color, ( now it changes with the polygon color), we might provide an option to assign one type of color to them, such as white or black, and transparency.
(3) Add an option to stroke transparency.
(4) Revise the stroke line width range from  0.1( now it starts from 1, by Marker Size Scale)

for Default value
(5) Set none for the Maker size column
(6) Set none for the Maker Color column
(7) uncheck Classify numerical color columns
(8) uncheck show Legend

**Comment by wybert** [comment]
- [x] (1) Add None to the base map option


for Stroke

- [ ] (2) Add an option to stroke color, ( now it changes with the polygon color), we might provide an option to assign one type of color to them, such as white or black, and transparency.
- [ ] (3) Add an option to stroke transparency.
- [ ] (4) Revise the stroke line width range from 0.1( now it starts from 1, by Marker Size Scale)

for Default value

- [ ] (5) Set none for the Maker size column
- [ ] (6) Set none for the Maker Color column
- [ ] (7) uncheck Classify numerical color columns
- [ ] (8) uncheck show Legend
