### ISSUE TITLE
Add Spatial Clustering category and node

### ISSUE THREAD

**Issue by UrbanGISer** [spatial-data-lab/knime-geospatial-extension#125]
This category is also called Regionalization, it might contain SKATE, AZP, REDCAP, MAXp, SCHC by PyGeoda, and Tools from MLR (Peano Curve, Mixed Level LR tool developed by Mu Lan and Fahui Wang)

**Comment by UrbanGISer** [comment]
Nodes are finished and  under polishing

**Comment by koettert** [comment]
List of nodes included in the 1.2 release:

- MSSC Initialization
- MSSC Refiner
- AZP
- Isolation Tackler
- MaxP
- Mean Center
- Peano Curve
- REDCAP
- SCHC
- Skater
- Standard Deviational Ellipse
