### ISSUE TITLE
Overlay function can not be used for generate cross points of two lines

### ISSUE THREAD

**Issue by UrbanGISer** [spatial-data-lab/knime-geospatial-extension#128]
Chang keep_geom_type to  False
https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.overlay.html#geopandas.GeoDataFrame.overlay

keep_geom_type
bool
If True, return only geometries of the same geometry type the GeoDataFrame has, if False, return all resulting geometries. Default is None, which will set keep_geom_type to True but warn upon dropping geometries.

**Comment by koettert** [comment]
@UrbanGISer  please add a test flow for this particular function

**Comment by koettert** [comment]
@koettert please review pull request: https://github.com/spatial-data-lab/knime-geospatial-extension/pull/129

**Comment by koettert** [comment]
Fixed with https://github.com/spatial-data-lab/knime-geospatial-extension/pull/129
