### ISSUE TITLE
Add "Has its center in" and "Contains the center of" in Spatial Join

### ISSUE THREAD

**Issue by UrbanGISer** [spatial-data-lab/knime-geospatial-extension#135]
HAVE_THEIR_CENTER_IN = (
            "Center within",
            """Matches if the left object's representative points intersect only with the interior of the right object 
            (not its boundary or exterior).""",
        )
        CONTAIN_CENTER_OF = (
            "Contain center",
            """Matches if the right object's representative points intersect only with the interior of the left object 
            (not its boundary or exterior).""",
        )
https://pro.arcgis.com/en/pro-app/latest/tool-reference/data-management/select-layer-by-location.htm

**Comment by koettert** [comment]
@koettert please review the pull request: https://github.com/spatial-data-lab/knime-geospatial-extension/pull/136

**Comment by koettert** [comment]
Pull request merged: https://github.com/spatial-data-lab/knime-geospatial-extension/commit/ca73c880dfebaf0fac474b916900d787782f7868
