### ISSUE TITLE
Nearest Join node to use harmonized distance settings

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#145]
The node should offer the user to define what distance unit he wants to use e.g. meter, kilometer or miles. 
Remove the CRS field and use instead the same logic as here:
https://github.com/spatial-data-lab/knime-geospatial-extension/issues/89

**Comment by UrbanGISer** [comment]
all the nodes were updated in the pull request
https://github.com/spatial-data-lab/knime-geospatial-extension/pull/116

    crs_info = knext.StringParameter(
        label="CRS for distance calculation",
        description=knut.DEF_CRS_DESCRIPTION,
        default_value="epsg:3857",
    )

    unitset = knext.StringParameter(
        label="Choose distance unit",
        description="The unit of distances. ",
        default_value="Meter",
        enum=[
            "Meter",
            "Kilometer",
            "Degree",
        ],
        since_version="1.1.0",
    )

**Comment by koettert** [comment]
Blocked by: https://github.com/spatial-data-lab/knime-geospatial-extension/issues/147

**Comment by koettert** [comment]
Fixed with https://github.com/spatial-data-lab/knime-geospatial-extension/commit/68f04e5c96210280684cd54267be018c2f83dd9a
