### ISSUE TITLE
GeoFile Reader fails to read in file written with the GeoFile Writer

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#148]
If I use the GeoFile Reader to read in a geojson file that I did write out with the GeoFile Writer I get the following exception: 
_Duplicate column names found: ['<RowID>', '<RowID>', 'area', 'geometry']_
For an example see: https://hub.knime.com/-/spaces/-/latest/~DIO5lPPwYuXwqv_d/

**Comment by UrbanGISer** [comment]
@koettert I can not replicate the error now with the. Did you already update the code:)

**Comment by koettert** [comment]
Fixed with this commit: https://github.com/spatial-data-lab/knime-geospatial-extension/commit/07f6258b740ed5227b7467fa97520b68cc56fa9c
