### ISSUE TITLE
Street Network Matrix node should use column selection panel instead of string input

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#149]
Is there a special reason why this parameter is string and not column? If not please use the ColumnParameter here as well.

**Comment by UrbanGISer** [comment]
I did not see the string input in the node, do you mean other nodes?

# input parameters
    O_geo_col = knext.ColumnParameter(
        "Origin Geometry Column",
        "Select the geometry column as origin.",
        # Allow only GeoValue compatible columns
        port_index=0,
        column_filter=knut.is_geo,
        include_row_key=False,
        include_none_column=False,
    )

    D_geo_col = knext.ColumnParameter(
        "Destination geometry column",
        "Select the geometry column as destination.",
        # Allow only GeoValue compatible columns
        port_index=1,
        column_filter=knut.is_geo,
        include_row_key=False,
        include_none_column=False,
    )

    R_geo_col = knext.ColumnParameter(
        "Road Network geometry column",
        "Select the geometry column as road network.",
        # Allow only GeoValue compatible columns
        port_index=2,
        column_filter=knut.is_geo,
        include_row_key=False,
        include_none_column=False,
    )
    R_speed_col = knext.ColumnParameter(
        "Speed column from Road Network",
        "Select the speed column from road network.",
        port_index=2,
        column_filter=knut.is_numeric,
        include_row_key=False,
        include_none_column=False,
    )

**Comment by koettert** [comment]
My bad I was on the wrong branch
