### ISSUE TITLE
Node to calculate line endpoints

### ISSUE THREAD

**Issue by UrbanGISer** [spatial-data-lab/knime-geospatial-extension#183]
new node to calculate endpoints for line feature

**Comment by UrbanGISer** [comment]
Pull request 183-line-endpoints

**Comment by UrbanGISer** [comment]
Please view the pull request

**Comment by koettert** [comment]
Solved with https://github.com/spatial-data-lab/knime-geospatial-extension/commit/af679f282fd9ea35851ad4eec137e96cc1a9a88f and following
