### ISSUE TITLE
Typo in the <osm boundary map> configuration and node description

### ISSUE THREAD

**Issue by sturmkev** [spatial-data-lab/knime-geospatial-extension#192]
In the field and also in the node description it says `Hierarchial` instead of `Hierarchical`.
The node description also uses `delimitated`, whereas it probably should say `delimited`.
![image](https://user-images.githubusercontent.com/116659033/230376711-d6c74c8e-c857-42a8-a025-c9d4371090e6.png)
![image](https://user-images.githubusercontent.com/116659033/230377101-244e9086-b375-4406-8447-233154c2597b.png)

**Comment by koettert** [comment]
Will be fixed with https://github.com/spatial-data-lab/knime-geospatial-extension/pull/115/commits/7724e58910886f2713b31136ec6e1165e4ff1033

**Comment by koettert** [comment]
Fixed with https://github.com/spatial-data-lab/knime-geospatial-extension/commit/0a4ef36efe5f93efb29b53d93613923141ee857d
