### ISSUE TITLE
Undefined variables in spatialnetwork file

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#221]
VS Code complains about undefined variables POI and key_col in the following line:
https://github.com/spatial-data-lab/knime-geospatial-extension/blob/40ef152aef2c662e93c71a1091a2ce1677ee45cd/knime_extension/src/nodes/spatialnetwork.py#L896

Can you please check if this is correct and fix it.

**Comment by UrbanGISer** [comment]
It is fine, becuse it will used in the      ```
 # combine origin and destination to single table
        POI = pd.concat([o_gdf, d_gdf], ignore_index=True)
```
