### ISSUE TITLE
Can't install knime-python-base on macbook m1

### ISSUE THREAD

**Issue by wybert** [spatial-data-lab/knime-geospatial-extension#24]
Can't install [knime-python-base](https://anaconda.org/knime/knime-python-base) on macbook m1.

python 3.10

- nothing provides requested knime-python-base

**Comment by koettert** [comment]
Can you please try the following to build your native M1 lokal environment:
`conda create -n my_new_env -c knime -c "knime/label/nightly" -c conda-forge knime-python-base ... other packages ...`

**Comment by wybert** [comment]
Yes, it works
