### ISSUE TITLE
ensure a uniform Coordinate Reference System (CRS) for GeoDataFrames in the Nearest Join node

### ISSUE THREAD

**Issue by UrbanGISer** [spatial-data-lab/knime-geospatial-extension#248]
ensure a uniform Coordinate Reference System (CRS) for both the left and right GeoDataFrames (pdf) in the Nearest Join node

**Comment by UrbanGISer** [comment]
Add a line to the main
`right_gdf = right_gdf.to_crs(left_gdf.crs)`

**Comment by UrbanGISer** [comment]
Apply short EPSG code to the result
`gdf.crs = gdf.crs.to_epsg()`

**Comment by UrbanGISer** [comment]
https://hub.knime.com/Center%20for%20Geographic%20Analysis%20at%20Harvard%20University/spaces/BugReport/latest/ProjGPKG~m8KTuwyzKJINi4LZ/

**Comment by UrbanGISer** [comment]
The Geopackage behavior of the released version seems to be different from our GitHub repository extension.  
In developing status:
Invalid projection: +INIT=EPSG:4326 +TYPE=CRS +type=crs: (Internal Proj Error: proj_create: crs not found)
In developing status:
GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]

**Comment by koettert** [comment]
Problem was in the test workflow that I updated. I only changed that the projection happens in place for the right gdf.
I couldn't reproduce the problem you mentioned above. If I read in the linked geo package file I see the GEOGCS... CRS and not the +INIT one which is as expected
