### ISSUE TITLE
Whether to keep the CRS uniform as epsg by applying  gdf.crs.to_epsg()

### ISSUE THREAD

**Issue by UrbanGISer** [spatial-data-lab/knime-geospatial-extension#252]
Do we need to build a class or utility for all nodes?
Apply short EPSG code to the result
gdf.crs = gdf.crs.to_epsg()

**Comment by UrbanGISer** [comment]
Just check KNIME 5.0, it is no longer an issue with the new CRS rending format

**Comment by koettert** [comment]
@koettert to check why the visualization is different in 5.0 and 4.7
