### ISSUE TITLE
Geospatial View to hide/disable settings if ignored for certain configurations

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#258]
The marker size scale setting is only use when no marker size column is selected. So if a column is selected the marker size setting should be disabled/hidden.

Depends on AP-19146

**Comment by koettert** [comment]
For a code example see this https://github.com/spatial-data-lab/knime-geospatial-extension/issues/266.

**Comment by wybert** [comment]
I may need more documents to implement this function.  I can't find the detailed document about the `OneOf` function. The example mentioned here only demonstrates for the presented columns, not for the data table column. A good idea the `classify the numerical color column settings` only appear when the numerical maker color column is being seleted.
