### ISSUE TITLE
Kepler.gl Geoview fails with multiple geometry columns in the input table

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#259]
As a workaround the user has to filter all geometry columns from the input table except the one he wants to view.
As a solution we should automatically filter all geometry columns except the selected one before sending the data to the Kepler view.

**Comment by koettert** [comment]
Instead of the MultiColumnFilter we should use the ColumnFilterParameter which should include all unknown columns by default.

**Comment by wybert** [comment]
> 

Is there any example we use in our code base?

**Comment by wybert** [comment]
> > 
> 
> @koettert Is there any example we use in our code base?

Never mind I just made a commit, please review it.

**Comment by koettert** [comment]
@wybert changed the filtering to use column names instead of appending pandas data frames which I think is more efficient. I also noticed that the ColumnFilterParameter did include also the selected geospatial column even though it wasn't shown in the ColumnFilterPanel. I have the hunch that the Python guys do not use the column_filter parameter in the `apply` method and having added the unknown columns option in the include side it includes the geospatial column as well. I will keep you posted
