### ISSUE TITLE
Can't update view in web portal when using the this extension and new Python script view

### ISSUE THREAD

**Issue by wybert** [spatial-data-lab/knime-geospatial-extension#262]
I can't update the component view when using this extension and the new Python script view when building a one-page data application.

I have built two workflows, you can download [here](https://drive.google.com/drive/folders/19Yhom808oujQDeNACjhc1ollIOupVJo-?usp=sharing). They perform the same function, which implements parsing the address entered by the user, and displays a table to display the address entered by the user and the resolved latitude and longitude coordinates, and a map to display the location of the address.

![image](https://github.com/spatial-data-lab/knime-geospatial-extension/assets/5254627/195e3841-8c5e-4ef9-82fd-1343d8143f31)

Notice that the data Apps both work well on Knime AP. But when uploading the Knime server, the two-page App works well but the one-page App doesn't work as expected.
See below for the one-page App in the Knime server,

![](https://raw.githubusercontent.com/spatial-data-lab/data/main/geocode.gif)

You can see, when I changed the address, the table was updated but the geospatial view was not updated.

The environment we have:
1. Knime server  4.16.4
2. Knime executor 4.7.4, connector version 4.16.1
3. knime-geospatial-extension 1.1.1

We have tried Knime Python Integration Python View too, they behave similarly to the Geo view in the knime-geospatial-extension. That is they can't update on a one-page data application in the Knime server.

**Comment by koettert** [comment]
Fixed with 5.1

**Comment by koettert** [comment]
Solved after Server Executor updated to 5.1
