### ISSUE TITLE
OSM Road Network node doesn't support multipolygons and is not stable

### ISSUE THREAD

**Issue by robertocadili** [spatial-data-lab/knime-geospatial-extension#265]
The OSM Road Network node currently seems to support only polygons, not multipolyongs. 

Suppose you'd like to retrieve the road network of the German state of Baden-Württemberg. With this node, it does not seem to be possible because the polygon obtained by OSM Boundary Map node is, in fact, a multipolygon. This is pretty annoying, especially because it's not predictable when we can expect a polygon or a multipolygon from the OSM Boundary Map node.

Additionally, the node does not seem to be very stable in extracting road networks if more then one place is provided. I tried to extract the road net of the cities of Freiburg and Singen, but the node only retrieved the road net of Freiburg as you can see in the map. I thought the order of the locations/polygons played a role but nothing changed.

Technical info: KNIME Analytics Platform v5.1

![image](https://github.com/spatial-data-lab/knime-geospatial-extension/assets/141317285/ec853913-1349-4080-8fee-cdb757ec0691)

**Comment by UrbanGISer** [comment]
revsied. Allow for MultiPolygon now, and cancel the function Add speed which is not stable

**Comment by koettert** [comment]
Fixed with https://github.com/spatial-data-lab/knime-geospatial-extension/commit/b451c3da8f3860b199e3a0151e9a314847cef758
