### ISSUE TITLE
Pulp is missing solver on Linux

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#289]
On Ubuntu Linux the Pulp solvers are not available.

**Comment by wybert** [comment]
> @koettert Install pulp on Mac and Linux using, `pip install pulp` The version I installed is pulp-2.7.0. It all passed the pulptest

**Comment by koettert** [comment]
Check if this also works on Windows and if it works update the geospatial_env:yml file accordingly

**Comment by koettert** [comment]
Fixed with https://github.com/spatial-data-lab/knime-geospatial-extension/commit/304ebda8a9b1fdc4bf91fbad3589652fa4a88c9e
