### ISSUE TITLE
"Make this Notebook Trusted to load map" prompt appears on each map view and configuration window

### ISSUE THREAD

**Issue by sturmkev** [spatial-data-lab/knime-geospatial-extension#29]
Whenever a configuration of a view node or a view output is opened, I see the screen below. It takes a moment until it disappears and the map is finally displayed.
What is the reason for this and how can we prevent this from being shown?
![image](https://user-images.githubusercontent.com/116659033/200286456-97fb8988-5881-47e8-86f3-5a74e43907a5.png)

**Comment by wybert** [comment]
Do you mean every view node? Which view node do you use?

**Comment by koettert** [comment]
@sturmkev what settings do you use in KNIME preferences JavaScript Views and which OS do you use? I guess this is a problem with the KNIME visualization framework. I also see this screen very briefly right before the map is loaded.

**Comment by sturmkev** [comment]
I am running KAP on Win10 and has CEF browser selected in the JavaScript Views prefereneces.

**Comment by koettert** [comment]
I guess this has been solved @sturmkev ?

**Comment by sturmkev** [comment]
Yes, I think so. At least I didn't face it recently anymore.
