### ISSUE TITLE
Support muliple crs in projection node

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#295]
3. Split Pandas Dataframe using groupby() function
The Pandas.groupby() function is used to split the DataFrame based on some values. First, we can group the DataFrame using the groupby() function after that we can select specified groups using the get_group() function. This is the best function when we want to split a DataFrame based on some column that has unique values.

**Comment by koettert** [comment]
Check out the code of the [MetadataNode](https://github.com/spatial-data-lab/knime-geospatial-extension/blob/main/knime_extension/src/nodes/conversion.py#L1291) for an example on how to access a table with mixed CRS

**Comment by UrbanGISer** [comment]
Please review the nodes. 
 For now, if it contains multiple CRS, the node will replace the geometry column. Append will not be applied here. 

Just information for reference:
I have tried to keep both， but it seems converting wkb back to KNIME pyarrow is not allowed。
        transformed_geometries.append(transformed_geom.wkb) 


```
arr_transformed_geom = pa.array(transformed_geometries, pa.binary()) 
t = t.append_column("transformed_geometry", arr_transformed_geom)
gdf = knio.Table.from_pyarrow(t)
knio.output_tables[0] = gdf
```

The data generated by KNIME Python is different from what normal Python does.
```
column2: [  -- is_valid: all not null  -- child 0 type: large_binary
    [
      000000000140340000000000004024000000000000,
      0000000001402E0000000000004024000000000000,
      01010000009F476EE86AFC40418E4A90F9A9123141,
      01010000006E6BA55CA07A39418E4A90F9A9123141,
      0101000000444B30F7F3554BC16EBDABD415537B41,
      010100000089F4D6630C6E46C12F13681286647B41
    ]  -- child 1 type: string
    [
      "EPSG:4326",
      "EPSG:4326",
      "EPSG:3857",
      "EPSG:3857",
      "EPSG:3060",
      "EPSG:3060"
    ]]

```
```
new: [[010100000000000000000034400000000000002440,01010000000000000000002E400000000000002440,010100000000000000000034400000000000002440,0101000000FFFFFFFFFFFF2D400000000000002440,0101000000BC515301000034401336B8FDFFFF2340
...
```
