### ISSUE TITLE
WARNING at start of <geospatial view> node configuration seems unnecessary

### ISSUE THREAD

**Issue by sturmkev** [spatial-data-lab/knime-geospatial-extension#30]
When configuring the _\<geospatial view\>_ node for the first time, the 'geometry' column is pre-selected. At the bottom of the (pre-)view we prompt a warning that this column is preset.
It seems to me, that this might be counter-intuitive, since the orange color might indicate that something is off.
I would think that we do not need to prompt this warning, since the user sees that the geometry column is selected at the top right. But this is just an idea.
![image](https://user-images.githubusercontent.com/116659033/200533276-4cb5c67c-d895-40c0-a6e7-fee14531847b.png)

**Comment by koettert** [comment]
I guess we could simply remove the warning in the `knime_utils `method if the column has been preset.
