### ISSUE TITLE
Nearest Join Node Add Exclusive Option from sjoin_nearest

### ISSUE THREAD

**Issue by rrousselot** [spatial-data-lab/knime-geospatial-extension#307]
I am having issues using the Nearest Join node because it only returns 1 item.  I am searching for proximity to nearest point that is not the current point I am at.  As it works now if the same point is in the dataset, you get a zero-distance returned and the record for the same point you are searching with.  I need the nearest point that is not the current point.  I think this can be solved by exposing the GeoPandas sjoin_nearest  parameter _exclusive_ to the nodes settings.  I believe this is currently always set to false.  Please make it possible to set this parameter in the Nearest Join node settings.  

https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.sjoin_nearest.html#geopandas.GeoDataFrame.sjoin_nearest

> exclusive
> bool, optional, default False
> If True, the nearest geometries that are equal to the input geometry will not be returned, default False. Requires Shapely >= 2.0

**Comment by koettert** [comment]
@UrbanGISer can you please check if this option solves the problem. If this is the case we could expose it with the next release as advanced setting.

**Comment by rrousselot** [comment]
FWIW I used a Python Script node to set the exclusive to True in sjoin_nearest and it worked the way I needed it to.

**Comment by koettert** [comment]
Perfect, thanks for the info @rrousselot . Will add the ticket to the next release
