### ISSUE TITLE
Support visualization layers in geo view nodes

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#313]
As a user I want to use visualization layers e.g. .lyrx or .qml file in the geo view node(s). I would like to store the current settings in such a file and import it e.g. in another node.

Forum request: https://forum.knime.com/t/node-to-store-layer-visualization/75610

Maybe we can utilize https://github.com/geostyler/geostyler for it

**Comment by koettert** [comment]
@wybert can you please have a look at this to see if this is feasible.

**Comment by wybert** [comment]
@koettert , we could export a JSON config file for the Geoview node through the node output port and also could accept a JSON file to replicate the style.

**Comment by koettert** [comment]
Another possible solution would be also to use the KNIME color manager information. However this would need to be supported by the Python framework first.

**Comment by koettert** [comment]
Will be solved by https://github.com/spatial-data-lab/knime-geospatial-extension/issues/113
