### ISSUE TITLE
Shorten auto generated projection CRS stings

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#314]
Relates to https://github.com/spatial-data-lab/knime-geospatial-extension/issues/279
We should use the to_epsg() method in the [auto projection method](https://github.com/spatial-data-lab/knime-geospatial-extension/blob/main/knime_extension/src/util/projection.py#L220) to shorten the generated CRS string. 

The problem with the current implementation is that when the proj+ CRS is converted to WKT-CRS which is only supported by the Java framework it gets inflated a lot. It would help the readability if we could prevent this by reducing it to a known epsg code.

**Comment by UrbanGISer** [comment]
See the Pull Request， it is a tiny update
