### ISSUE TITLE
How to read GADM geopackage files with the 

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#35]
I tried to read a GADM geopackage file with the GeoPackage Reader node but failed. With different error messages. What do I need to specify as the Input layer name for reading (Has also a typo).

**Comment by koettert** [comment]
Would GADM be a good data source for our Open Data nodes? Could be integrated via https://pypi.org/project/gadm/

**Comment by UrbanGISer** [comment]
Sure, We can include GADM as a data source. I check the sample data, you should use GeoFile Reader to read that. Originally, GeoFile is designed to read single-layer files, Geopackage read a layer in the Geopackage.

**Comment by UrbanGISer** [comment]
I revise the GeoPackage Reader to allow empty or wrong layer information, It also can read the GDB files as well. It can read all kinds of GADM file
