### ISSUE TITLE
Column <RowID>_right in the result of Spatial Join in KNIME AP 5.3.0, but not in KNIME AP 5.2.2

### ISSUE THREAD

**Issue by UrbanGISer** [spatial-data-lab/knime-geospatial-extension#363]
I found a column of <RowID>_right was kept in the result of Spatial Join in KNIME AP 5.3.0 with the test workflow. but when I used  KNIME AP 5.2.2, it disappeared.

I can not figure out the reason. To make it simpy, we can drop the <RowID> column before applying spatial join.

        left_gdf.reset_index(drop=True, inplace=True)
        right_gdf.reset_index(drop=True, inplace=True)

Nearest Join also has similar behavior.

**Comment by koettert** [comment]
@koettert try if the testworkflow for the Spatial Join and Nearest Join to see if it also fails for you

**Comment by koettert** [comment]
@UrbanGISer just executed the SpatialJoin, NearestJoin and NearestJoin2 testflow and all return the expected columns. What OS are you using?

**Comment by koettert** [comment]
Can't reproduce.
