### ISSUE TITLE
Multiple base maps in Geospatial View not working in 5.4.0/1.3.0

### ISSUE THREAD

**Issue by sturmkev** [spatial-data-lab/knime-geospatial-extension#378]
When changing the base map inside the Geospatial View node, many of them seem not to be working anymore, leaving one left with the OSM base map only. This is a list of unsupported maps:
- CartoDB
- ESRI
- Gaode
- NASAGIBS
- Stamen
- Strava

The error message is the following:
`Execute failed: Custom tiles must have an attribution.`

KNIME Analytics Platform: 5.4.0
Geospatial Extension: 1.3.0

<img width="1017" alt="Screenshot 2024-12-11 at 15 03 17" src="https://github.com/user-attachments/assets/6eb99c26-a3be-41f9-afb8-299ca3a84dc7" />

**Comment by koettert** [comment]
Will be addressed with: https://github.com/spatial-data-lab/knime-geospatial-extension/pull/377

**Comment by koettert** [comment]
Fixed with https://github.com/spatial-data-lab/knime-geospatial-extension/commit/8b06dd726c48efdcc65a5987c6ab46a67d0f223f
Will be released with 1.3.1
