### ISSUE TITLE
Collection of spatial network nodes e.g. for drive distance calculations

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#38]
As a user I want to calculate the drive distance rather than the Euclidean between two places. To compute the distance I want to use a free service such as OSM but also want to use commercial providers such as here.com, Google API.

**Comment by UrbanGISer** [comment]
I have created an OSRM-based node, it can be used for acquiring driving distance and duration and route without API,  temporarily it can get distance and duration for 100 OD/ per second in geolab.py

**Comment by koettert** [comment]
@UrbanGISer is working on the third node OSRM Route that creates a multi line string representing the shortest path along the streets.

**Comment by UrbanGISer** [comment]
Now the OSRM node works now, but I still created an issue in the OSRM Github to confirm their capacity to accept the web API request.

https://github.com/Project-OSRM/osrm-backend/issues/6527
