### ISSUE TITLE
Reverse geocoding support

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#40]
As a user I want to get the address of a geo coordinate. To do so I want to use a free provider such as OSM but also commercial once such as here.com or Google.
The input of the node would be a table with geo coordinate (point) and the node would append new columns to each row with the corresponding address.
This was requested during the summit and in the [KNIME forum](https://forum.knime.com/t/geospatial-point-intersection-on-polygons-query/58629).

**Comment by koettert** [comment]
We might be able to use the https://geopy.readthedocs.io/en/stable/ library for this

**Comment by koettert** [comment]
- Preset geometry column. For an example see [here](https://github.com/spatial-data-lab/knime-geospatial-extension/blob/main/knime_extension/src/nodes/calculation.py#L67)
- Configure should return output table spec with unique result column name. For an example see [here](https://github.com/spatial-data-lab/knime-geospatial-extension/blob/main/knime_extension/src/nodes/calculation.py#L67)
- Default service_provider value is wrong since the keys are all lower case
- Improve node description e.g. state that API key is optional depending on the selected service
- I would suggest to use an enum shared with the geocoding node with a selection of most common services instead of geopy.geocoders.SERVICE_TO_GEOCODER.keys(). This way we can handle service specific parameters if required e.g. if API key is needed or not e.g. using nominatim now fails with init() got an unexpected keyword argument 'api_key'. We can also add more info e.g. the link to the service a nicer user facing name e.g. OpenStreetMap vs Nomatim and maybe a flag if it is free or commercial
- Do not rename the geo column (line 743) but keep the original name and use the `geo_col` parameter when working with the column. Use the `knime_util.load_geo_data_frame()` method to get the GeoDataFrame
- Line 749 should be `self.api_key` I guess
- Create a test for each search service
- Icon is missing

**Comment by UrbanGISer** [comment]
Icon  added;  Line 749 revised ;

**Comment by koettert** [comment]
Just tested the node and I think it would help people if we also add the raw JSON result string as an extra column in addition to the address column. This would help to extract only a particular part of the address e.g. city as requested [here ](https://forum.knime.com/t/geospatial-point-intersection-on-polygons-query/58629).
