### ISSUE TITLE
US2020 Tiger Map node fails for some requests e.g. New York (36) or District of Columbia (11)

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#45]
Getting errors when trying to execute US2020 TIGER Map node. Two types of error messages depending on what I want to do:

Execute failed: HTTP Error 404: Not Found or 

Execute failed: An error occurred while calling o15.reportBatchWritte

Node works fine for some states (e.g., configuring the node to extract all tract20 for Florida or Maryland works fine, but fails when trying for New York (36) or District of Columbia (11). Also tried different data type like tract, block group, etc., node just fails. 

I checked archive ([Index of /geo/tiger/TIGER2020PL/STATE](https://www2.census.gov/geo/tiger/TIGER2020PL/STATE/) ) and was able to download the zipped archive for New York manually.

**Comment by UrbanGISer** [comment]
Thanks, I revised the dictionary in which there existed wrong state names. (e.g. , YORK for NEW _YORK  )  for District of Columbia (11). it has a different folder structure, I add a line to consider the situation.
