### ISSUE TITLE
US2020 Tiger Map node produces corrupt output table for specific queries

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#46]
Depending on the query the output table can’t be viewed (it gets stuck at “Loading port content…”. In addition, when wanting to reset the node, the following error is shown: Error when attempting to close open closeable.WARN  ResetAction Reset not allowed

Node config: 
- State FIPS: 01
- County FIPS: 01 (same as State FIPS because I want all counties of state 01)
- TIGER/line data type: county20

The node execute successfully but I can’t use it for further processing (tried Joiner node and Geospatial View node)

See example workflow here: https://hub.knime.com/tobias.koetter/spaces/Geospatial/latest/bugs/Faulty%20exection%20Tiger%20Map%20node~p65jSa5GEUA_THX_

**Comment by UrbanGISer** [comment]
In the updated Tiger nodes with revised FIPS dictionary, it is fine now
