### ISSUE TITLE
Geospatial View and Spatial Heatmap fail if table contains special characters

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#48]
It seems that the Geospatial View and Spatial Heatmap do not escape special characters when creating the GeoJSON stringe e.g. the following input string creates an exception I guess because of the {} brakets:
I didnâ€™t want to do it. but I did it anyway. I looked at the Town Halls. {{{what a mess}}} they are so different. #Biden is a gentle caterpillar while #Trump is a rabid fox ðŸ¥º #TownHalls #trustYourInstinct  #election2020 #holdontight #bumpyride

Example workflow can be found here: https://hub.knime.com/tobias.koetter/spaces/Geospatial/latest/bugs/ViewsWithUnescapedStringProblem~m87FqNLk_gM68CYx

**Comment by wybert** [comment]
This is a bug from geopandas, I open an issue there  https://github.com/geopandas/geopandas/issues/2657 
We could escape user input string in their data before feeding in geopandas. Do you think this would be a good solution?

**Comment by koettert** [comment]
@wybert  could you fix this problem directly in Geopandas and send them a pull request?

**Comment by koettert** [comment]
Changed to 1.1 in the hope that the pull request has been merged until then

**Comment by koettert** [comment]
Awesome congratulation. Looks like the fix will be part of 0.13. Let's hope they release it soon. Once released and we have updated to our extension we can close the ticket.

**Comment by koettert** [comment]
Geopandas 0.12 has not been release yet: https://github.com/geopandas/geopandas/releases

**Comment by koettert** [comment]
Fixed with the update to GeoPandas 0.13 in this commit: https://github.com/spatial-data-lab/knime-geospatial-extension/commit/83bc8a346946fcee6e693f737e86f859bee337cf
