### ISSUE TITLE
Add most commonly used projection with short description to knime_utils.DEF_CRS_DESCRIPTION

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#50]
As a lay user I have no clue about which projection to use. That is why we should add the most common globally useable projections to the CRS description and what they are for e.g. EPSG:3857 for distances in meters.

**Comment by UrbanGISer** [comment]
add the explanation of 4326 and 3857 for the world map, 4269 and 26918 for north america, 4490 and 4479 for China
