### ISSUE TITLE
OSM Road Network should use reproduceable order of list items

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#52]
Right now the order of list values is unpredictable maybe due to the usage of the toString() method. Instead the node should use a reproduceable way to generate the string from a list e.g. by sorting the elements prior converting to string.

**Comment by koettert** [comment]
Fixed problem with list element order. However test is still failing due to different number of rows.

**Comment by koettert** [comment]
@UrbanGISer can you please have a look at your test flow why it does return different number of results.

**Comment by UrbanGISer** [comment]
It works fine now when using the newly updated codes in Python Script !!, please try the test workflow in our KNIME hub Space
