### ISSUE TITLE
Additional information for node description might be helpful on “US2020 Tiger Map” node.

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#57]
As one needs to type in FIPS for state (and county) it might be helpful to include this additional link to the node description to let unexperienced users understand the states/counties and their corresponding FIPS. As one needs to type in FIPS for state (and county) it might be helpful to include this additional [link](https://www2.census.gov/geo/pdfs/maps-data/data/tiger/tiger2006se/app_a03.pdf) to the node description to let unexperienced users understand the states/counties and their corresponding FIPS.

In addition include some of the most common counties (e.g. New York) as an example into the node description.

**Comment by UrbanGISer** [comment]
FIPS code-related information was added to utils and opendata nodes as well
