### ISSUE TITLE
Add node to create grid on map using Uber H3

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#60]
The [H3 library from Uber](https://www.uber.com/en-DE/blog/h3/) provides a nice way of creating a world wide grid that can be used to aggregate information on different levels of granularity. The node would allow the user to create such a grid for a certain area.

This blog post shows a nice example on how to use the library: https://towardsdatascience.com/uber-h3-for-data-analysis-with-python-1e54acdcc908

**Comment by rrousselot** [comment]
If you do this, you should have a _Lat/Lon to Hex Index_ node and an _H3 Index to Geometry_ Node.  The _H3 Index to Geometry_ node should have the option to return the centroid.  I think with these two nodes, you would cover 90% of use cases.

**Comment by koettert** [comment]
@rrousselot we have just merged the new node to the main branch. We will release a single "Create H3 Grid" node which will receive as input a polygon which defines the area to fill with the H3 grid and will return a table with the H3 Cell Index column and the hexagon as geometry column. Using the existing geospatial nodes such as Centroid and Spatial join should help to solve most problems. Do you have any use case that couldn't be solved with this information?

**Comment by rrousselot** [comment]
If I understand what you have done correctly, your method doesn't really align with the idea that a point can be converted to an H3 cell.  The Uber library has two simple and fast functions to accomplish this.  The first h3.latlng_to_cell(lat, lng, resolution) returns the index (cell) for the point based on the resolution selected.  Then, if needed, h3.cell_to_boundary(cell, geo_json=False) takes the cell string and returns a polygon for that point.  What you describe is a method for filling in areas with hex, which may be useful to someone but not really how H3 are used.  H3s are defined as "H3 is a geospatial INDEXING system that partitions the world into hexagonal cells." emphasis added.   

What you describe is the h3.polygon_to_cells(polygons, res, geo_json_conformant=False) function.

**Comment by koettert** [comment]
@rrousselot thanks for the info. Makes sense. I created a new issue to implement another node which supports your use case:  https://github.com/spatial-data-lab/knime-geospatial-extension/issues/325
