### ISSUE TITLE
US Census and Tiger maps node with links in option description

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#61]
The new node dialogs have a little icon next to each dialog option. To make it easier for people to find the right MIPS etc numbers it would be great if we could add a link to a lookup page to the corresponding dialog option so that the link is shown directly in the node dialog when clicking on the question mark of the option.

**Comment by UrbanGISer** [comment]
Add a hyperlink of the FIPS code list onto the icon links of the census and tiger node
