### ISSUE TITLE
Add more visualization options to Spatial Heatmap

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#63]
Add visualization settings from the Geospatial View to the Heatmap view e.g. color and legend settings. Show the heatmap settings (weight, opacity, zoom, radius, blur) as first group in the dialog followed by the visualization settings from the Geospatial View.

Create a new settings class for the general options (base map, stroke, marker size, tooltip, popup) in the Geospatial View node to reuse it also in the Heatmap View along with the other existing settings groups e.g. Coloring Settings and Legend Settings.

**Comment by wybert** [comment]
I added colormap base map and legend settings options.
