### ISSUE TITLE
<buffer> does not pre-select the geometry column

### ISSUE THREAD

**Issue by sturmkev** [spatial-data-lab/knime-geospatial-extension#65]
When adding a _\<buffer\>_ node to the workflow and connecting it to a table with a geometry column, it doesn't pre-select the geometry column (even though there is only one) and hence, the node is in an unconfigured state.

**Comment by UrbanGISer** [comment]
revise that by adding code in configure:     self.geo_col = knut.column_exists_or_preset(
            configure_context, self.geo_col, input_schema, knut.is_geo
        )
