### ISSUE TITLE
<clip> fails if the mask is not covering any of the features of the input table - changing outcome handling

### ISSUE THREAD

**Issue by sturmkev** [spatial-data-lab/knime-geospatial-extension#66]
If one wants to mask out data (e.g. points) and is not aware that the mask (lower input port) actually does not cover any features of the input table (upper input port) the node fails with the following message:
`ERROR Clip                 5:59       Execute failed: ('Did not pass numpy.dtype object', 'Conversion failed for column geometry with type geometry')`

I think we would need one of the following two options here.
a) The node fails in such a situation but delivers a more meaningful message to the user, like "Mask does not cover any of the input features".
b) The node runs successfully but delivers a warning, like "Node created an empty table (Mask does not cover any of the input features)".

Workflow to test:
https://hub.knime.com/kevin_sturm/spaces/examples-geo/latest/clip-mask-not-covering-data~Qa_GTL7h76FMW23o

**Comment by koettert** [comment]
Will be fixed by KNIME in ticket AP-19627

**Comment by UrbanGISer** [comment]
with a try function and raise ValueError, it is solved. A test workflow was uploaded here
https://hub.knime.com/sdls%20team/spaces/Workflow%20Tests/latest/Manipulation/ClipTest~7qEbO0kyvaUicXQU
     try:
            gdf_clipnew = gp.clip(left_gdf, right_gdf, keep_geom_type=True)
            r = knext.Table.from_pandas(gdf_clipnew)
        except:
            raise ValueError("Improper Mask Geometry")
