### ISSUE TITLE
<geofile writer> does not pre-select the geometry column

### ISSUE THREAD

**Issue by sturmkev** [spatial-data-lab/knime-geospatial-extension#74]
When adding a _\<geofile writer\>_ node to the workflow and connecting it to a table with a geometry column, it doesn't pre-select the geometry column (even though there is only one. Even though. the node is in a configured state.

**Comment by koettert** [comment]
Fixed with https://github.com/spatial-data-lab/knime-geospatial-extension/commit/2647688b3109563d9923c883af4e827738cfd2d1
