### ISSUE TITLE
putting a <geospatial view> node into a component doesn't show the view but opens a download window

### ISSUE THREAD

**Issue by sturmkev** [spatial-data-lab/knime-geospatial-extension#75]
If I put a _\<geospatial view\>_ into a component it generally gives me the view in the composite view. Now that I expanded the component, changed some connections (introduced flow variable connections) and created the component again, I get a pop-up window which asks me to download the index.html whenever a _\<geospatial view\>_ is executed. I am not entirely sure if I can reproduce but I will keep the affected workflow.

![image](https://user-images.githubusercontent.com/116659033/205315724-59f247c3-1a5d-4809-b793-edeeecc23f62.png)

**Comment by koettert** [comment]
I guess this has been solved @sturmkev ?

**Comment by sturmkev** [comment]
Yeah, I also didn't face the issue anymore recently.
