### ISSUE TITLE
Hovering on elements  Geospatial View will generate a warning as ERROR CEFNodeView 

### ISSUE THREAD

**Issue by UrbanGISer** [spatial-data-lab/knime-geospatial-extension#76]
while hovering on elements in the dynamic view window of Geospatial View Nodes, it keeps generating the warning message

ERROR CEFNodeView                     Uncaught TypeError: Cannot read properties of undefined (reading 'properties') (source: http://org.knime.core.ui.view/view_5_12/index.html; line: 169)

see the example workflow of ClipTest
https://hub.knime.com/-/spaces/-/latest/~7qEbO0kyvaUicXQU/

**Comment by koettert** [comment]
Seems to be fixed with the lates KNIME version.
