### ISSUE TITLE
replace_external_js_css error in heatmap view node

### ISSUE THREAD

**Issue by wybert** [spatial-data-lab/knime-geospatial-extension#77]
While fixing another issue we have in the heatmap view. I added legend and colormap for the node, I think this function needs other javascript libraries in addition to leaflet, like d3.js. 

> ERROR CEFMiddlewareService            No resource found for 'http://org.knime.core.ui.view/view_4_1661/libs/leaflet/1.6.0/d3.min.js/'. Most likely an implementation error.
ERROR CEFNodeView                     Uncaught SyntaxError: Unexpected identifier (source: http://org.knime.core.ui.view/view_4_1661/libs/leaflet/1.6.0/d3.min.js/; line: 1)
ERROR CEFNodeView                     Uncaught ReferenceError: d3 is not defined (source: http://org.knime.core.ui.view/view_4_1661/index.html; line: 172)

For now, I comment on the following code to make sure it works fun, but maybe we can add the js and CSS path for d3.js too like for leaflet

```python
  html = map.get_root().render()
  # html = replace_external_js_css_paths(
  #     r"\1./libs/leaflet/1.6.0/\3\"\4",
  #     html,
  # )
```

**Comment by koettert** [comment]
Ok I will have a look at it tomorrow before creation be the release build.
Thanks

--

**Comment by koettert** [comment]
Fixed with: https://github.com/spatial-data-lab/knime-geospatial-extension/commit/ec414f3cb76e7ac810006361fb900f666f5cfd5e
