### ISSUE TITLE
Enable reading online GDB or GPKG

### ISSUE THREAD

**Issue by UrbanGISer** [spatial-data-lab/knime-geospatial-extension#85]
GeoPackage Reader can read the local file， we should add the capacity for reading online zipped GDB and GPKG

**Comment by koettert** [comment]
Opened an [issue](https://github.com/Toblerity/Fiona/issues/1167) with the Fiona developers because latest version cause problem with reading online files.
For now we will wait for the Fiona guys.

**Comment by koettert** [comment]
Might be a problem with the Python version. With version 3.7 it worked but the 3.9 version we use right now it does not work. @UrbanGISer will try again with the latest 3.9.x version to see if the error still exists

**Comment by UrbanGISer** [comment]
New Fiona 1.19
https://github.com/Toblerity/Fiona/issues/1167#issuecomment-1476388547

From the website:
this is no longer an issue for Fiona 1.9.2, which will be released today.

Finished processing dependencies for Fiona==1.9.2.dev0
(venv) $ python
Python 3.11.0 (main, Nov  2 2022, 11:35:09) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fiona
>>> path="zip+https://raw.githubusercontent.com/UrbanGISer/Test/main/Case05new.gdb.zip"
>>> fiona.listlayers(path)
['MSA574', 'MSAPCP', 'MSA570F', 'MSAtimeF', 'MSAtime', 'MSA570', 'MSAfinal', 'MSA_Bkg_570', 'MSAPCP0509', 'MSAtime510', 'MSAfinal1', 'MSA2svca', 'MSA2svca20m', 'TwoStepVCATable2', 'TwoStepVCATable3']

**Comment by UrbanGISer** [comment]
access                    1.1.8              pyhd8ed1ab_0    conda-forge
affine                    2.4.0              pyhd8ed1ab_0    conda-forge
amply                     0.1.5              pyhd8ed1ab_0    conda-forge
arrow-cpp                 9.0.0           py39h660e0c4_29_cpu    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
aws-c-auth                0.6.26               h1262f0c_1    conda-forge
aws-c-cal                 0.5.21               h7cda486_2    conda-forge
aws-c-common              0.8.14               hcfcfb64_0    conda-forge
aws-c-compression         0.2.16               h8a79959_5    conda-forge
aws-c-event-stream        0.2.20               h5f78564_4    conda-forge
aws-c-http                0.7.6                h2545be9_0    conda-forge
aws-c-io                  0.13.19              h0d2781e_3    conda-forge
aws-c-mqtt                0.8.6               hd211e0c_12    conda-forge
aws-c-s3                  0.2.7                h8113e7b_1    conda-forge
aws-c-sdkutils            0.1.8                h8a79959_0    conda-forge
aws-checksums             0.1.14               h8a79959_5    conda-forge
aws-crt-cpp               0.19.8              he6d3b81_12    conda-forge
aws-requests-auth         0.4.2                      py_0    conda-forge
aws-sdk-cpp               1.10.57              h64004b3_8    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
blosc                     1.21.3               hdccc3a2_0    conda-forge
boost-cpp                 1.78.0               h9f4b32c_3    conda-forge
boto3                     1.26.109           pyhd8ed1ab_0    conda-forge
botocore                  1.29.110           pyhd8ed1ab_0    conda-forge
branca                    0.6.0              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                hcfcfb64_8    conda-forge
brotli-bin                1.0.9                hcfcfb64_8    conda-forge
brotlipy                  0.7.0           py39ha55989b_1005    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
c-ares                    1.18.1               h8ffe710_0    conda-forge
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cairo                     1.16.0            hd694305_1014    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39h68f70e3_3    conda-forge
cfitsio                   4.2.0                h9ebe7e4_0    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3           win_pyhd8ed1ab_2    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.3              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.7            py39h1f6ef14_0    conda-forge
cryptography              40.0.1           py39hb6bd5e6_0    conda-forge
curl                      7.88.1               h68f0423_1    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
debugpy                   1.6.7            py39h99910a6_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
deprecation               2.1.0              pyh9f0ad1d_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
dill                      0.3.6              pyhd8ed1ab_1    conda-forge
docutils                  0.19             py39hcbf5309_1    conda-forge
esda                      2.4.3              pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                h63175ca_1    conda-forge
fiona                     1.9.2            py39hb5a1417_0    conda-forge
folium                    0.14.0             pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.39.3           py39ha55989b_0    conda-forge
freetype                  2.12.1               h546665d_1    conda-forge
freexl                    1.0.6                h67ca5e6_1    conda-forge
gdal                      3.6.3            py39h3be0312_1    conda-forge
geopandas                 0.12.2             pyhd8ed1ab_0    conda-forge
geopandas-base            0.12.2             pyha770c72_0    conda-forge
geos                      3.11.2               h1537add_0    conda-forge
geotiff                   1.7.1                hb4c6682_7    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
gflags                    2.2.2             ha925a31_1004    conda-forge
giddy                     2.3.4              pyhd8ed1ab_0    conda-forge
glog                      0.6.0                h4797de2_0    conda-forge
glpk                      5.0                  h8ffe710_0    conda-forge
hdf4                      4.2.15               h1334946_6    conda-forge
hdf5                      1.12.2          nompi_h57737ce_101    conda-forge
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.3.0              pyha770c72_0    conda-forge
importlib-resources       5.12.0             pyhd8ed1ab_0    conda-forge
importlib_metadata        6.3.0                hd8ed1ab_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
inequality                1.0.0                      py_0    conda-forge
ipykernel                 6.22.0             pyh025b116_0    conda-forge
ipython                   8.12.0             pyh08f2357_0    conda-forge
ipywidgets                8.0.6              pyhd8ed1ab_0    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jsonlines                 1.2.0              pyh9f0ad1d_2    conda-forge
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter_client            8.1.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.0            py39hcbf5309_0    conda-forge
jupyterlab_widgets        3.0.7              pyhd8ed1ab_0    conda-forge
kealib                    1.5.0                h61be68b_0    conda-forge
keplergl                  0.3.2              pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.4            py39h1f6ef14_1    conda-forge
knime-extension           5.0.0                      py_0    knime
knime-python-base         4.7.0           py39_202212081031    knime
krb5                      1.20.1               heb0366b_0    conda-forge
lcms2                     2.15                 h3e3b177_1    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libabseil                 20230125.0      cxx17_h63175ca_1    conda-forge
libaec                    1.0.6                h63175ca_1    conda-forge
libblas                   3.9.0           5_hd5c7e75_netlib    conda-forge
libbrotlicommon           1.0.9                hcfcfb64_8    conda-forge
libbrotlidec              1.0.9                hcfcfb64_8    conda-forge
libbrotlienc              1.0.9                hcfcfb64_8    conda-forge
libcblas                  3.9.0           5_hd5c7e75_netlib    conda-forge
libcrc32c                 1.1.2                h0e60522_0    conda-forge
libcurl                   7.88.1               h68f0423_1    conda-forge
libdeflate                1.17                 hcfcfb64_0    conda-forge
libexpat                  2.5.0                h63175ca_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgdal                   3.6.3                hd256549_1    conda-forge
libglib                   2.74.1               he8f3873_1    conda-forge
libgoogle-cloud           2.8.0                hf2ff781_1    conda-forge
libgrpc                   1.52.1               h32da247_1    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libjpeg-turbo             2.1.5.1              hcfcfb64_0    conda-forge
libkml                    1.3.0             hf2ab4e4_1015    conda-forge
liblapack                 3.9.0           5_hd5c7e75_netlib    conda-forge
libnetcdf                 4.9.1           nompi_h83fa41b_102    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libpq                     15.2                 ha9684e8_0    conda-forge
libprotobuf               3.21.12              h12be248_0    conda-forge
libpysal                  4.7.0              pyhd8ed1ab_0    conda-forge
librttopo                 1.1.0               he1da8c1_13    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libspatialite             5.0.1               h2bb424f_24    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libssh2                   1.10.0               h9a1e1f7_3    conda-forge
libthrift                 0.18.1               h9ce19ad_0    conda-forge
libtiff                   4.5.0                hc3b8658_5    conda-forge
libutf8proc               2.8.0                h82a8f57_0    conda-forge
libwebp-base              1.3.0                hcfcfb64_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.10.3               hc3477c8_6    conda-forge
libzip                    1.9.2                h519de47_1    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
llvmlite                  0.39.1           py39hd28a505_1    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mapclassify               2.5.0              pyhd8ed1ab_1    conda-forge
markdown                  3.4.1              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.2            py39ha55989b_0    conda-forge
matplotlib-base           3.7.1            py39haf65ace_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mgwr                      2.1.2                      py_0    conda-forge
momepy                    0.5.4              pyhd8ed1ab_0    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munch                     2.5.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
numba                     0.56.4           py39hadaa1c4_1    conda-forge
numpy                     1.23.5           py39hbccbffa_0    conda-forge
openjpeg                  2.5.0                ha2aaf27_2    conda-forge
openssl                   3.1.0                hcfcfb64_0    conda-forge
osmnx                     1.3.0              pyhd8ed1ab_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandarallel               1.6.4              pyhd8ed1ab_0    conda-forge
pandas                    1.5.2            py39h2ba5b7c_2    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.5.0            py39haa1d754_0    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              3.2.0              pyhd8ed1ab_0    conda-forge
pointpats                 2.3.0              pyhd8ed1ab_0    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
poppler                   23.03.0              h934c637_1    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                15.2                 hd87cd2b_0    conda-forge
proj                      9.1.1                heca977f_2    conda-forge
prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
psutil                    5.9.4            py39ha55989b_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pulp                      2.7.0            py39hcbf5309_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py4j                      0.10.9.7           pyhd8ed1ab_0    conda-forge
pyarrow                   9.0.0           py39hdb2b141_29_cpu    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygeoda                   0.0.8.post1      py39h2e07f2f_0    conda-forge
pygeos                    0.14             py39h4440df4_1    conda-forge
pygments                  2.15.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyproj                    3.5.0            py39he478073_0    conda-forge
pyrsistent                0.19.3           py39ha55989b_0    conda-forge
pysal                     23.1               pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.9.15          h4de0772_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      3_cp39    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pywin32                   304              py39h99910a6_2    conda-forge
pyyaml                    6.0              py39ha55989b_5    conda-forge
pyzmq                     25.0.2           py39hea35a22_0    conda-forge
quantecon                 0.5.3              pyhd8ed1ab_0    conda-forge
quilt3                    5.2.1              pyhd8ed1ab_0    conda-forge
rasterio                  1.3.6            py39h156e9e9_0    conda-forge
rasterstats               0.14.0                     py_0
re2                       2023.02.02           h63175ca_0    conda-forge
requests                  2.28.2             pyhd8ed1ab_1    conda-forge
requests-futures          1.0.0              pyh9f0ad1d_2    conda-forge
rtree                     1.0.1            py39h09fdee3_1    conda-forge
rvlib                     0.0.6            py39h90537b9_2    conda-forge
s3transfer                0.6.0              pyhd8ed1ab_0    conda-forge
scikit-learn              1.2.2            py39hb6325b5_1    conda-forge
scipy                     1.10.1           py39hfbf2dce_0    conda-forge
seaborn                   0.12.2               hd8ed1ab_0    conda-forge
seaborn-base              0.12.2             pyhd8ed1ab_0    conda-forge
segregation               2.3.1              pyhd8ed1ab_1    conda-forge
setuptools                67.6.1             pyhd8ed1ab_0    conda-forge
shapely                   2.0.1            py39h4440df4_1    conda-forge
simplejson                3.19.1           py39ha55989b_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               hfb803bf_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
spaghetti                 1.7.2              pyhd8ed1ab_0    conda-forge
spglm                     1.0.8                      py_0    conda-forge
spint                     1.0.7              pyhd8ed1ab_0    conda-forge
splot                     1.1.5.post1        pyhd8ed1ab_0    conda-forge
spopt                     0.5.0              pyhd8ed1ab_0    conda-forge
spreg                     1.3.2              pyhd8ed1ab_0    conda-forge
spvcm                     0.3.0                      py_0    conda-forge
sqlite                    3.40.0               hcfcfb64_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
statsmodels               0.13.5           py39hc266a54_2    conda-forge
sympy                     1.11.1             pyh04b8f61_3    conda-forge
tenacity                  8.2.2              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tiledb                    2.13.2               h3132609_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tobler                    0.9.0              pyhd8ed1ab_0    conda-forge
tornado                   6.2              py39ha55989b_1    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
traittypes                0.2.1              pyh9f0ad1d_2    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unicodedata2              15.0.0           py39ha55989b_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
vc                        14.3                hb6edc58_10    conda-forge
vs2015_runtime            14.34.31931         h4c5c07a_10    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.7              pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
xerces-c                  3.2.4                h63175ca_2    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xyzservices               2023.2.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hcfcfb64_4    conda-forge
zstd                      1.5.2                h12be248_6    conda-forge

**Comment by UrbanGISer** [comment]
name: geospatial_env
channels:
  - knime
  - conda-forge
dependencies:
  - packaging
  - python=3.9
  - curl=7.88.1 #required by libgdal which includes an older version with vulnerabilities
  - fiona=1.9.2
  - folium=0.14.0*
  - geopandas=0.12.2
  - geopy=2.3.0*
  - ipykernel=6.22.0 #required by kepler but not included in its dependencies it seems
  - keplergl=0.3.2
  - knime-extension
  - knime-python-base
  - libgdal=3.6.3
  - libpysal=4.7.0
  - mgwr=2.1.2
  - numpy=1.23.5 #required to fix problem with latest version of numpy
  - osmnx=1.3.0
  - pulp=2.7.0
  - pyproj=3.5.0
  - pysal=23.1
  - rasterio=1.3.6
  - seaborn=0.12.2
  - shapely=2.0.1
  - pygeoda 0.0.8
  - pointpats 2.3.0
  - pip=23.0.1
  - pip:
    - pyecharts==2.0.2

**Comment by UrbanGISer** [comment]
Close issue as it is solved

**Comment by koettert** [comment]
@UrbanGISer I created a branch with the new dependency versions and did run the workflow tests. It seems as if the package reader no longer works as expected. At least in this [workflow](https://hub.knime.com/-/spaces/-/latest/~jkRsglLumYEmQ3yI/) it no longer returns the geometry column. Can you please recreate your environment with the env file from the branch and execute the linked test flow and if it fails investigate why.

**Comment by koettert** [comment]
Fixed with https://github.com/spatial-data-lab/knime-geospatial-extension/commit/a0d65bf98e270b1633f7cab93bb2fcc124fa1e7b
