### ISSUE TITLE
US2020 Census Data node should have option to output US2020 TIGER Map compatible GEO_ID column

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#87]
As a user I need to use a string manipulation node after the US2020 Census Data node to convert the GEO_ID column values to be compatible to the GEO_ID values from the US2020 TIGER Map node. The performed operation is 
`regexReplace($GEO_ID$,".*US" ,"")`
Ideally the US2020 Census Data node provides an option to either replace the existing GEO_ID format with the compatible one or be appending a new GEO_ID_TIGER column. Which version to use depends on if the original Census GEO_ID is also used elsewhere and of interest to join with other resources or not. Do we know what 1400000US means? Does it contain any useful information?

**Comment by UrbanGISer** [comment]
As they have the same format , I add a code to both nodes US2020 Census Data and US ACS 5 years
        if "GEO_ID" in gdf.columns:
            gdf["GEO_ID"] = gdf["GEO_ID"].str.replace(r".*US", "", regex=True)

**Comment by koettert** [comment]
@koettert check and close

**Comment by koettert** [comment]
@UrbanGISer we need to be very cautious to make sure that nodes are backward compatible between versions. Otherwise we will break existing workflows which we should prevent at all costs!

We could either deprecate the node which I think is to drastic but instead I would suggest to add a new dialog option to the Census Data node that allows users to decide if they want to strip the US part from the GEO ID. Maybe we can call it "Make GEO.ID Tiger/Line compatible". The process of stripping the first nine characters to make it Tiger compatible is also explained [here](https://www.census.gov/programs-surveys/geography/guidance/geo-identifiers.html) at the bottom of the page so we could also use a faster `substring` method instead of a regex to create a compatible GEO.ID.

For new nodes the setting is _true_ by default but for existing nodes the setting is _false_. Please have a look at the [Python docu](https://docs.knime.com/latest/pure_python_node_extensions_guide/index.html#extension-versioning) to see how this can be done.

**Comment by koettert** [comment]
Fixed with https://github.com/spatial-data-lab/knime-geospatial-extension/pull/117
