### ISSUE TITLE
Harmonize distance unit usage in buffer nodes

### ISSUE THREAD

**Issue by koettert** [spatial-data-lab/knime-geospatial-extension#89]
Ideally the nodes that are sensitive to the distance unit of the CRS e.g. buffer we should show in the node dialog the distance unit e.g. meter or degree. Beginners might not know that the current CRS uses degree and enter meters for the distance.

Also Multiple Ring Buffer provides the user with an option to specify the unit even though it does not check that the CRS is a meter based projection. So we should harmonize the different buffer nodes.

**Comment by UrbanGISer** [comment]
Add a CRS code to identify whether it is a projected or geographic CRS

from pyproj import CRS  # For CRS units check

crsinput = CRS.from_user_input(gdf.crs)
if crsinput.is_geographic:
    knext.ConfigurationContext.set_warning(
        "Unit as Degree, Please use Projected CRS"
    )

**Comment by koettert** [comment]
For all nodes that use distance e.g. Nearest Join, Buffer, area and length... do the following:

- Add a radio button to the node dialog where the user can choose the distance unit (meter[default], degree)
- If the user selected distance unit is the same as the projection unit -> all good we proceed as before
- If the user selected distance unit is different from the projection unit -> use default CRS and re-project the input column and add a node warning (`config_context.set_warning()`)  that the input data was re-projected to match the selected unit

Warning message will look like this: CRS unit does not match using default CRS epsg:3857 (epsg:4326)

**Comment by koettert** [comment]
Fixed with https://github.com/spatial-data-lab/knime-geospatial-extension/commit/0f48e87345234774327e17574a2565df00fe505d and https://github.com/spatial-data-lab/knime-geospatial-extension/commit/6c5901f26cde2765df3b1289067ec6108775eaee
