### ISSUE TITLE
change default start location of a kepler.gl view to the extent of the data to be displayed

### ISSUE THREAD

**Issue by sturmkev** [spatial-data-lab/knime-geospatial-extension#96]
Currently, the _\<kepler.gl geoview\>_ node starts displaying the data in San Francisco, CA so one needs to zoom out first to see the actual data, which might be located somewhere else.
If the library already contains a method to do so, it would be appreciated to enable it. Otherwise the node would need to calculate the extent of the input data geometry and paste it into config dictionary like so: https://stackoverflow.com/questions/70082494/changing-the-default-start-location-of-a-map-in-keper-gl

**Comment by koettert** [comment]
@wybert do you think this is a smaller issue that we could fix with the 1.1 release? If so please add the Milestone tag and fix it. Thanks

**Comment by wybert** [comment]
I will fix it before the next minor release 1.1.

**Comment by koettert** [comment]
Thanks @wybert
